name: Trigger ${{ github.event.inputs.trigger }}
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      trigger:
        description: 'Trigger event'     
        required: true
        default: 'manual'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Trigger:
    name: Trigger ${{ github.event.inputs.trigger }}
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Show trigger source
        run: |
            echo "Trigger source: ${{ github.event.inputs.trigger }}"   
